Reset `isStaticValue` for each variable
Esri/adlib pull request #54
Opened 2020-10-20 18:31 UTC by MikeTschudi

#53

2020-10-20 18:37 UTC, MikeTschudi commented
@tomwayson, would you please review this PR?

2020-10-20 18:39 UTC, tomwayson approved these changes

2020-10-28 14:53 UTC, tomwayson requested changes
I'm revoking my review and asking @dbouwman to review, merge, and release this since he's more familiar w/ the code and consequences of the changes.

2020-10-28 16:49 UTC, dbouwman approved these changes
Since all existing tests pass... presumably this will not incur a breaking change...

2020-10-28 16:49 UTC, merged

2020-10-28 16:53 UTC, MikeTschudi commented
And there's a new test that breaks without the modification:
```js
test('Adlib::Hierarchies:: missing value with defaults does not stop processing', (t) => {
  let template = {
    msg: '{{organization.name||My Community}}<br />{{organization.nonexistantproperty.sharedTheme.logo.small||https://www.arcgis.com/sharing/rest/content/items/28989a5ecc2d4b2fbf62ac0f5075b7ff/data}}<br />{{organization.name||My Community}}',
  }

  var settings = {
    organization: {
      name: "myOrg"
    }
  };

  let result = adlib(template, settings)

  t.plan(1);
  t.equal(result.msg, 'myOrg<br />https://www.arcgis.com/sharing/rest/content/items/28989a5ecc2d4b2fbf62ac0f5075b7ff/data<br />myOrg');
  t.end();
})
```